apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devboard-kks
spec:
  selector:
    app: devboard-backend
  ports:
    - protocol: TCP
      port: 8080  # service
      targetPort: 8080 # pod port
