apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devboard-kks
spec:
  clusterIP: None  # This creates a headless service
  selector:
    app: devboard-postgres
  ports:
    - protocol: TCP
      port: 5432  # service
      targetPort: 5432 # pod port
